### ISSUE TITLE
Could you upgrade this addon to version 2.1?

### ISSUE THREAD

**Issue by cjdduarte** [lovac42/WarriorMode#1]
Sorry, but I had no other way to get in touch.

Could you upgrade this addon to version 2.1?
https://ankiweb.net/shared/info/441235634

**Comment by lovac42** [comment]
Hi, that's not my project. You can contact the author here: https://www.reddit.com/user/Dayjaby/
It would take me a much longer time to study his code.

**Comment by cjdduarte** [comment]
I had already contacted, but the author did not respond.
